### ISSUE TITLE
wpf support

### ISSUE THREAD

**Issue by furesoft** [rionmonster/Glyphfriend#101]
pls add wpf support

**Comment by rionmonster** [comment]
Hi @furesoft,

Unfortunately, it doesn't look like this is going to be possible to do significant differences between the HTML-flavored editor, which Glyphfriend currently leverages, and the one designed for WPF. It would likely require an entirely separate extension to be written to support it.

Should this change - I'll be open to supporting such a scenario (if the demand is there), but at this time, I don't think it's viable.
