### ISSUE TITLE
Support for Visual Studio 2019

### ISSUE THREAD

**Issue by rionmonster** [rionmonster/Glyphfriend#102]
Add support for Visual Studio 2019 (with any necessary changes and underlying DLLs)

**Comment by Liebeck** [comment]
@rionmonster Is there any update on the compatibility? I just found the aweseome extension but it can't be installed for VS 2019, unfortunately :-/ I would love to use it

**Comment by mr-awk** [comment]
@rionmonster Any updates?

**Comment by rionmonster** [comment]
Hey folks,

Firstly, _thank you_ for you patience. I know it's been a long time since I've been around (two kids does that to you).

I'm going to be closing this issue since I finally managed to get some time together and write the extension to support Visual Studio 2019. You can find it [here](https://marketplace.visualstudio.com/items?itemName=RionWilliams.Glyphfriend2019) or by simply searching for it from the Extensions > Manage Extensions area in Visual Studio.

Please let me know if you run into anything. I'm going to be culling through the backlog and updated all of the supported libraries (as well as potentially adding some more) in the coming weeks.

**Comment by Liebeck** [comment]
Hi @rionmonster,

thank you very much! I'm really looking forward to using the extension. I just tried it out with one of my projects.

Upon removing the `fa-sing-out-alt` and retyping it, there seems to a download and then an exception:
`<i class="fas fa-sign-out-alt"></i>`

This is should be the error from the error log. Can you take a quick look? ;)

  ```
<entry>
    <record>848</record>
    <time>2020/01/23 21:33:12.838</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: source&#x000D;&#x000A;   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)&#x000D;&#x000A;   at Glyphfriend.GlyphCompletionListProvider.GetEntries(HtmlCompletionContext context)&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Html.Editor.Completion.HtmlCompletionSource.&lt;&gt;c__DisplayClass12_1.&lt;PopulateCompletionList&gt;b__0()&#x000D;&#x000A;   at Microsoft.WebTools.Languages.Shared.Editor.Utility.GuardedOperations.InvokeExtensionPoint(Object errorSource, Action action)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

**Comment by rionmonster** [comment]
Interesting.

I know that during development I ran into that one time but it seemed like it was an environmental issue. Could you try deleting the following folder and reopening Visual Studio?

```
%LocalAppData%l\Microsoft\VisualStudio\16.x
```
Let me know if that addresses the problem.

CC: @madskristensen - Any idea what might be causing this or know of someone that could possibly take a look at it?

**Comment by Liebeck** [comment]
Unfortunately, no. I renamed the directory which resetted VS to default. Installed your extension again. Upon first typing "fa-" there seems to be a delay to load a list but then I just see the default blue cube. The error log shows the same error but I don't have the "an extension crashed yadada" error bar at the top of visual studio anymore.

I'm using VS Community 2019 Version 16.4.2. Let me know If I can be of more help ;)

**Comment by rionmonster** [comment]
That's really strange. I'll look into it tonight and see if I can reproduce it and see if someone from the Visual Studio crew might have some ideas.

**Comment by Liebeck** [comment]
Thank you very much for your time and effort! ❤

**Comment by rionmonster** [comment]
Hi @Liebeck,

I'm attaching an early release of Glyphfriend to this post that you can try installing to see if that addresses your issue. I spoke with a few members of the Visual Studio team to get their recommendations so hopefully this will work:

- [Glyphfriend.VS2019-PreviewBuild.zip](https://github.com/rionmonster/Glyphfriend/files/4110930/Glyphfriend.VS2019-PreviewBuild.zip)

Just change the extension of the attached file from a `.zip` to a `.vsix` and you should be able to install it locally.

Please let me know (either way) once you get a chance to try it.

Thanks,

Rion
