### ISSUE TITLE
Backwards Compatibility with earlier Visual Studio Versions

### ISSUE THREAD

**Issue by Rionmonster** [Rionmonster/Glyphfriend#15]
After initial release, make the necessary changes to target older versions of Visual Studio (or at least 2013).

**Comment by AMgdy** [comment]
+1

**Comment by Misiu** [comment]
+1

**Comment by Rionmonster** [comment]
While backwards compatibility isn't possible due to functionality differences and API changes between Visual Studio 2013 and Visual Studio 2015, support for 2013 is still planned when time is available.

A [repository has been created here](https://github.com/Rionmonster/Glyphfriend2013) for this project and I will update it as progress is made.
