### ISSUE TITLE
Map css file name to font toolkit

### ISSUE THREAD

**Issue by ernesto-angel** [Rionmonster/Glyphfriend#21]
I happen to combine FontAwesome and Bootstrap into one css file.  It would be nice if there was a way to specify name of css file and font toolkit.

**Comment by Rionmonster** [comment]
Thanks for the input Ernesto,

A while back I had been working on a more dynamic version of Glyphfriend that would actually detect specific glyph-related files and generate the images on the fly (storing them in a cache for future referencing), however this might be a bit different than that.

What you are referring to would be something that I have given some thought to recently and it would be a more generic GlyphCompletionProvider that would map specific prefixes to certain libraries (i.e. it would know that `fa-*` referred to Font Awesome or `fi-*` referred to Foundation) as opposed to mapping to specific files.

I'll give it some thought as I am planning on making some updates to Glyphfriend when I get the chance (which hopefully will be soon).

**Comment by Rionmonster** [comment]
Closing this for now. It may be revisited in the future, but currently the default file names will be used for each of the libraries.
