### ISSUE TITLE
Incompatible with ReSharper?

### ISSUE THREAD

**Issue by Huntk23** [Rionmonster/Glyphfriend#22]
I installed this extension but it doesn't seem to be working. Do you happen to know if there is a compatibility issue having ReSharper installed?

**Comment by JoshuaGarrison27** [comment]
I am having this problem as well. I have ReSharper 10 installed.

**Comment by Rionmonster** [comment]
I haven't tested it thoroughly with Resharper installed, but I suppose it could be possible for some type of conflict to occur (as Resharper handles quite a bit of completion events on it's own). 

I'll look into it.

**Comment by JoshuaGarrison27** [comment]
Awesome. Thank you! Keep us posted if you don't mind. This is an awesome project.

**Comment by Rionmonster** [comment]
I still have yet to test this using ReSharper, but I have a feeling that if it isn't working, it is likely that Resharper is simply overtaking all of Visual Studio's default Completion events (i.e. Intellisense). 

You could possibly try resolving this issue by going into the Options section of Resharper in Visual Studio and trying to explicitly disable it for HTML files. This should allow Visual Studio and Glyphfriend to take the reins in those areas and work.

I'll try testing it when I get a chance, but you might be able to get to it before I can.

**Comment by Huntk23** [comment]
Hi Rion,

I went ahead and turned this into a Resharper Extension (not fully implemented like yours) since the Resharper IntelliSense is completely overriding Visual Studios.

https://github.com/Huntk23/ResharperGlyphfriend
https://resharper-plugins.jetbrains.com/packages/Hunt.ResharperGlyphfriend/0.6.0

I added a **thanks** for this great idea in the Readme

Thanks Rion

**Comment by gpriaulx** [comment]
Even with Resharper 10 installed, the Visual studio intellisense still supports this plugin. I tend to use the VS default and press Shift+Alt+Space for Resharper's when needed. Worse case scenario, you could invert this, and trigger it on shortcut.

**Comment by Rionmonster** [comment]
@Huntk23 

Wow. That's great Kelby! I've actually been looking into this issue and working on it locally but haven't had a chance to push anything out to GitHub (with regards to a complete Glyphfriend extension for Resharper), but I am glad to see that you use it enough to think of making a R# extension to handle it.

Great job!

**Comment by Rionmonster** [comment]
@gpriaulx 

I've noticed the same thing. Resharper appears to support it, but it seems inconsistent at times. I've generally just gone into the Options area and disabled Resharper Intellisense for HTML completion (as I feel that Visual Studio does just fine in that department). This option has been my go-to work around and recommendation for folks that run into issues, assuming this is an acceptable option.

**Comment by LukaszRabiec** [comment]
@Huntk23 
How to install your plugin in VS 2015 and ReSharper Ultimate 2016.2? I try this: [Solution](https://resharper-support.jetbrains.com/hc/en-us/articles/207241675-Offline-plug-in-installation-process), but it doesn't work. In the ReSharper Gallery in VS i have only 53 extensions (without yours).
