### ISSUE TITLE
Support for GitHub Glyphs in Markdown

### ISSUE THREAD

**Issue by hashhar** [Rionmonster/Glyphfriend#23]
This would come handy for blog systems relying on Markdown for content generation.

I would like to work on it. But I have my exams right now, so maybe a month later.
PS: I actually wanted to get some idea about how the extension works so that I can get up to speed quicker.

**Comment by Rionmonster** [comment]
Hi @hashhar!

Could you elaborate a bit more on what "GitHub" glyphs are? Glyphfriend already supports the [Octicons](https://octicons.github.com/) library, which appears to be what you are referring to. If there is another library that you are referring to, let me know.

**Comment by hashhar** [comment]
I am talking about this, https://github.com/jekyll/jemoji.

I can try and work on this but I have a lot of issues I need to look into. No Visual Studio SDK, no prior experience in developing extensions and I don't know much about how to render emoji.

**Comment by Rionmonster** [comment]
Hi again @hashhar,

I wanted to let you know that last night I decided to spend a few minutes digging into this type of behavior and it appears to be totally doable. 

Emoji support in general is going to be quite a bit different than the way that Glyphs are handled. The Emoji images are just that, images, whereas the other types of Glyphs that are used within the application are generally mapped to CSS files within the current solution, which are then mapped to images, so a different type of provider must be used to trigger the Intellisense to pick them up.

In the [develop branch](https://github.com/Rionmonster/Glyphfriend/blob/develop), I've started implementing this type of functionality. I've converted all of the supported Emojis that you referenced earlier into 16x16, optimized PNG files (which Visual Studio likes) and have built the necessary components to pick them up.

The only issue that I am currently encountering is a minor problem with the Markdown files not triggering the appropriate provider (and thus triggering the Intellisense completion events), but I'll try to dig into it some more this evening and let you know how that goes.

Thanks again for the great suggestion.

**Comment by hashhar** [comment]
Thanks for working on it. And thanks for the insight about how emoji and glyphs work.

**Comment by Rionmonster** [comment]
Hi @hashhar 

I just wanted to let you know that this feature has been completed and was added into the most recent release of Glyphfriend! You can see an example of it in action within the `README.md` file as well.

Thanks again for the suggestion and if you have any other suggestions or improvements, please feel free to let me know.

**Comment by hashhar** [comment]
Awesome! I just tried it out and it works great. Thanks for this.
