### ISSUE TITLE
Material Design Icons

### ISSUE THREAD

**Issue by svekl** [Rionmonster/Glyphfriend#25]
Hi, thank you for great extension.
What about adding support of nice Material Design Icons Set? 
https://materialdesignicons.com/

**Comment by Rionmonster** [comment]
@svekl 

Thanks for the recommendation. I plan on adding support for this and a few other popular libraries within the next release.

**Comment by Rionmonster** [comment]
Closing as this will be resolved in Issue #29.

**Comment by Rionmonster** [comment]
@svekl 

I wanted to let you know that this should be available within the [latest release of Glyphfriend](https://github.com/Rionmonster/Glyphfriend/releases/tag/v1.3). 

Thanks again for the great suggestion!

**Comment by svekl** [comment]
Great news, thank you for awesome extension!
