### ISSUE TITLE
Entypo support

### ISSUE THREAD

**Issue by mnguyen284** [rionmonster/Glyphfriend#56]
Hi,

I'm using this theme from bootstrap which uses Entypo.

https://bootstrap-themes.github.io/marketing/docs/index.html#entypo

Because now Entypo doesn't come with a font and css, I don't know how to make Glyphfriend recognize the library.

Please suggest.

Thank you,
Minh

**Comment by rionmonster** [comment]
Hi @mnguyen284,

Thanks for reporting this. The fix itself should be fairly straight-forward as the library already support the Entypo library, so it would just be a matter of explicitly targeting the Bootstrap themes via the `GlyphCSSDefinitionExpression` property of the provider. This would allow Entypo glyphs to be picked up by either Entypo or the Bootstrap themes explicitly.

I'll throw together something for this when I have some time at lunch today.

**Comment by mnguyen284** [comment]
Hi,

Thanks for your respond. My workaround was taking the Entypo part from the theme css and put into entypo.css. Not elegant but it works.
