### ISSUE TITLE
Question: Is the Intellisense supposed to work on plain html files 

### ISSUE THREAD

**Issue by Sibz** [rionmonster/Glyphfriend#66]
I am using latest update of VS 2015, have installed this plug-in however I am using plain old html files and I can't seem to get and Intellisense other that what is defined/used in the current document.

I am taking a guess that this is not how this plugin functions, but could you please clarify, and let me know if there is another was to make it possible.

**Comment by rionmonster** [comment]
Do you have any of the supported libraries included within your project? Basically, the way that the extension works is that it will search your current project for any of the supported library files (e.g. font-awesome.css, octicons.css, bootstrap.css, etc.) and it will load the those glyphs behind the scenes and handle the replacement when the completion event occurs (i.e. Intellisense).

So if you just have an .html file on its own, Glyphfriend likely wouldn't pick it up.

**Comment by Sibz** [comment]
Yeah I have the bootstrap.css file, and that is included in the link element in my main html file.
I have this working in another project, the difference being this project is an empty website template and I havn't added MVC/WebAPI.
Also Bootstrap is install manually (well kind of, I use gulp to download from CDN and put into my scripts/css folders - and its been manually added to the project in the solution explorer).

**Comment by rionmonster** [comment]
I believe that I may know what could be causing this and I think that there is an issue with how Glyphfriend actually searches for CSS files (and it generally does this within a "Project") so I feel that it may not be just searching the entire solution itself. This could cause it to not work for non-Projects (e.g. MVC/Web API applications).

I'm currently in the process of getting Glyphfriend up and running on the next version of Visual Studio, but I'll make an issue for this an look into it.

**Comment by Sibz** [comment]
Bootstrap.min.css is under the same project as my html file.
This is my basic structure:
`content/dist/css` -bootstrap.min.css in here
`content/dist/html` -partial html files in here
`content/dist/js` 
`index.html` -Full html document
The hinting doesn't work in the partial files or the main index file.

**Comment by Sibz** [comment]
I have solved the issue - I have included  bootstrap.css  in the project as well as bootstrap.min.css and I now have intellisense.

**Comment by rionmonster** [comment]
@Sibz 

This had been addressed in the latest version of the extension. You can now use Glyphfriend in a File > New HTML File scenario without the need for any dependencies in your project. Your libraries will still need to be accessible at run-time (either via a CDN or directly referencing the appropriate file), but from a tooling perspective, it'll give you the autocompletion that you need.
