### ISSUE TITLE
1.5.80 doesn't install

### ISSUE THREAD

**Issue by thoemmi** [rionmonster/Glyphfriend#68]
Glyphfriend 1.5.80 for VS2015 doesn't install, because **license.txt** is missing. The installer log says:
```18.11.2016 09:10:49 - Microsoft VSIX Installer
18.11.2016 09:10:49 - -------------------------------------------
18.11.2016 09:10:49 - Initializing Install...
18.11.2016 09:10:49 - Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException: The package does not contain the software license agreement that is specified in the extension manifest (LICENSE.txt).
   at Microsoft.VisualStudio.ExtensionManager.ExtensionHeaderImpl.get_License()
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
I guess this issue was introduced in 68dad1ab3aed2aafc44ef913f63903ab6c5b9bca

**Comment by rionmonster** [comment]
Ah, this was introduced within the `vs15` branch, which has become obsolete recently. If you want to get the latest version, you should be able to find Glyphfriend within Visual Studio under **Extensions and Updates > Online > Visual Studio Gallery > Glyphfriend 2015**.

The most recent version is 1.5.4.0.

**Comment by thoemmi** [comment]
I'm using the Open VSIX feed (http://vsixgallery.com/feed/), which offers me the version 1.5.80 of Glyphfriend. My current version of Glyphfriend is 1.5.70. I don't want to remove the Open VSIX feed because I use it for many other extensions.

**Comment by rionmonster** [comment]
Well that explains it, there's currently an issue with some of the changes within the extension and Appveyor, which handles the VSIX Gallery uploads / feed. I'm looking into this and hopefully will get it resolved soon.

**Comment by modulexcite** [comment]
thanks for an excellent extension, i have a similar problem with installing the new version 1.5.80 on Visual Studio Professional Update 3 on Windows 7 SP1.

**Comment by AlonAm** [comment]
same here
![image](https://cloud.githubusercontent.com/assets/3127610/20526267/0507b9fc-b0cc-11e6-994a-e990d3d0da8e.png)

**Comment by rionmonster** [comment]
Hi @AlonAm 

As previously mentioned, this is an issue with Appveyor and it's support, or lack thereof, for Visual Studio 2017 projects. Glyphfriend was recently refactored to include both versions for 2015 and 2017 along with a common codebase. However, when the project is built, Appveyor doesn't know how to understand / differentiate between the two and things blow up. 

I'm honestly not sure how some of the builds from the non-develop/master branches snuck their way into the Appveyor feed, but I'm working on resolving the issue. 

If you need to use Glyphfriend in the mean-time, you can always download the proper version directly from the Visual Studio gallery within the IDE.

**Comment by AlonAm** [comment]
@rionmonster that's good to know, I'm in the process of upgrading [AnyStatus](https://marketplace.visualstudio.com/items?itemName=AlonAmsalem.AnyStatus) to support VS2017...

**Comment by rionmonster** [comment]
Yeah, it's a bit of a process (or at least it was during the pre-release stage) but if you need any help, let me know as I might be able to answer questions if you have any issues.

**Comment by AlonAm** [comment]
thank you, I will.

**Comment by rionmonster** [comment]
This issue should now be resolved with the latest rewrite of the extension to 2.0. The previous issues pertaining to Appveyor-based feeds should also be resolved after quite a few discussions with the folks there.

If you encounter any additional issues, check your installed version number and ensure that it is at least 2.0. If it is, please consider opening up an issue and I'll investigate it further.

Thanks for all of your help and feedback, it's appreciated.
