### ISSUE TITLE
Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.

### ISSUE THREAD

**Issue by Cholo981** [rionmonster/Glyphfriend#90]
- Microsoft VSIX Installer
07/04/2017 09:05:38 - -------------------------------------------
07/04/2017 09:05:38 - vsixinstaller.exe version:
07/04/2017 09:05:38 - 15.0.26228.0 built by: D15REL
07/04/2017 09:05:38 - -------------------------------------------
07/04/2017 09:05:38 - Command line parameters:
07/04/2017 09:05:38 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,d:\download\Glyphfriend.VS2015 (1).vsix
07/04/2017 09:05:38 - -------------------------------------------
07/04/2017 09:05:38 - Microsoft VSIX Installer
07/04/2017 09:05:38 - -------------------------------------------
07/04/2017 09:05:38 - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\ssms.exe: Impossibile trovare un punto di ingresso con nome '?' nella DLL 'PkgdefMgmt.dll'.
07/04/2017 09:05:38 - Initializing Install...
07/04/2017 09:05:38 - Dettagli estensione...
07/04/2017 09:05:38 - 	Identifier         : 950d05f7-bb25-43ce-b682-44b377b5307d
07/04/2017 09:05:38 - 	Name               : Glyphfriend 2015
07/04/2017 09:05:38 - 	Author             : Rion Williams
07/04/2017 09:05:38 - 	Version            : 2.1.0.2
07/04/2017 09:05:38 - 	Description        : Glyphfriend is a Visual Studio extension to enhance the existing Intellisense to display preview glyphs for many of the common glyph-based font libraries like Font Awesome, Material Design, Octicons, and more.
07/04/2017 09:05:38 - 	Locale             : en-US
07/04/2017 09:05:38 - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=RionWilliams.Glyphfriend
07/04/2017 09:05:38 - 	InstalledByMSI     : False
07/04/2017 09:05:38 - 	SupportedFrameworkVersionRange : [4.5,)
07/04/2017 09:05:38 - 
07/04/2017 09:05:38 - 	SignatureState     : Unsigned
07/04/2017 09:05:38 - 	Prodotti supportati : 
07/04/2017 09:05:38 - 		Microsoft.VisualStudio.Enterprise
07/04/2017 09:05:38 - 			Version : [14.0,15.0)
07/04/2017 09:05:38 - 		Microsoft.VisualStudio.Community
07/04/2017 09:05:38 - 			Version : [14.0,15.0)
07/04/2017 09:05:38 - 		Microsoft.VisualStudio.Pro
07/04/2017 09:05:38 - 			Version : [14.0,15.0)
07/04/2017 09:05:38 - 

07/04/2017 09:05:38 - 		-------------------------------------------------------
07/04/2017 09:05:38 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
07/04/2017 09:05:38 - 		Name         : Visual Studio core editor
07/04/2017 09:05:38 - 		Version      : [14.0,16.0)
07/04/2017 09:05:38 - 

07/04/2017 09:05:38 - 	Extension is not signed.
07/04/2017 09:05:38 - 

   in VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   in VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   in VSIXInstaller.App.Initialize()
   in System.Threading.Tasks.Task`1.InnerInvoke()
   in System.Threading.Tasks.Task.Execute()

**Comment by rionmonster** [comment]
Thanks for reporting this.

I'm not entirely sure how this happened, but it looks like the 2015 version of the extension 'Glyphfriend 2015'  is either installed (or attempting to be installed) on Visual Studio 2017, which uses the updated 'Glyphfriend 2017' extension.

If it's already installed, try removing the 2015 version from the "Extensions and Updates" menu and installing the 2017 version from the same location. This should fix your issue.

I'll look into how and why this could have possibly happened (as you shouldn't even be able to install the 2015 version on VS2017).

**Comment by Cholo981** [comment]
Perfect, thank you.
