### ISSUE TITLE
VS2015 Web Essentials 2015.3 Duplicate Context Menu Items in Code Editor

### ISSUE THREAD

**Issue by raulreveche** [rionmonster/Glyphfriend#92]
Greetings! When editing an HTML file, Web Essentials context menu items in the VS2015 CE code editor are duplicated after installing Glyphfriend 2015. The context menus return to normal after disabling or uninstalling Glyphfriend and restarting VS2015. Please have a look at this [URL](http://stackoverflow.com/questions/43549713/vs2015-web-essential-duplicate-context-menu-in-code-editor) to see a screen capture from another guy at Stackoverflow who I think has the same issue.

Your program is very useful. =)

**Comment by rionmonster** [comment]
Closing this due to age (and from what I recall it being a conflict between the two extensions)
