### ISSUE TITLE
Not working in Visual Studio 2017

### ISSUE THREAD

**Issue by tblack2200** [rionmonster/Glyphfriend#98]
I just downloaded\installed GlyphFriends 2017 and it does not work.  Auto-complete does not display the icon and there is no right-click menu.

Thanks

**Comment by HassanGulzar** [comment]
Same issue here. I'm working on Bootstrap 4 with FA v4.7.0 but Glyphfriend is not even activating. Same goes for Bootstrap icons as well. I don't know about VS2015 as I'm new to this extension.

**Comment by VibertJ** [comment]
Same issue for me in GlyphFriends 2017. 
I found a temporary solution : I can have the contextual menu if I put "HTML Editor (Default)" in the Open With dialog.
![image](https://user-images.githubusercontent.com/1779350/39138567-828c2b7e-4720-11e8-8a32-c2cefbdbebdc.png)

**Comment by rionmonster** [comment]
As mentioned by others, it's very likely that this could have resulted due to a conflict with Resharper. I've been out of pocket (or at least away from this project) for a bit for personal reasons (kids == no free time), but if this issue is still arising, please let me know.

Thanks much,

Rion
